export const SERVICES = [
  { id:"musculoskeletal", category:"Physiotherapy & Rehabilitation", name:"Musculoskeletal Physiotherapy", subServices:["Back Pain","Knee Pain","Arthritis"], icon:"🦴", description:"Expert treatment for bones, joints, muscles and connective tissues.", duration:"45 min" },
  { id:"post-operative", category:"Physiotherapy & Rehabilitation", name:"Post-operative Rehabilitation", subServices:["Hip Replacement Recovery","Knee Surgery Recovery","Shoulder Surgery Recovery"], icon:"🏥", description:"Structured recovery programs after surgical procedures.", duration:"60 min" },
  { id:"sports-injury", category:"Physiotherapy & Rehabilitation", name:"Sports Injury Rehabilitation", subServices:["Ligament Tears","Muscle Strains","Joint Dislocations"], icon:"⚽", description:"Targeted rehab for athletes and active individuals.", duration:"45 min" },
  { id:"neurological", category:"Physiotherapy & Rehabilitation", name:"Neurological Rehabilitation", subServices:["Stroke","Cerebral Palsy"], icon:"🧠", description:"Specialized therapy for neurological conditions.", duration:"60 min" },
  { id:"exercise-therapy", category:"Physiotherapy & Rehabilitation", name:"Exercise Therapy", subServices:["Strength Training","Balance Training","Flexibility Programs"], icon:"🏋️", description:"Therapeutic exercise programs for recovery and wellness.", duration:"45 min" },
  { id:"manual-therapy", category:"Core Services", name:"Manual Therapy & Dry Needling", subServices:["Joint Mobilization","Soft Tissue Massage","Dry Needling / Trigger Points"], icon:"🖐️", description:"Hands-on techniques to relieve pain and improve mobility.", duration:"45 min" },
  { id:"electrotherapy", category:"Core Services", name:"Electrotherapy", subServices:["TENS Therapy","Ultrasound Therapy","NMES"], icon:"⚡", description:"Electrical modalities for pain relief and muscle stimulation.", duration:"30 min" },
  { id:"home-care", category:"Home Based Care", name:"Home Based Care", subServices:["Home Physiotherapy Sessions","Post-Hospital Discharge Care","Elderly & Palliative Care","Chronic Condition Management at Home"], icon:"🏠", description:"Professional physiotherapy delivered in the comfort of your home.", duration:"60 min", badge:"Available Citywide" },
  { id:"preventative-care", category:"Core Services", name:"Preventative Care", subServices:["Posture Assessment","Ergonomic Consultation","Injury Prevention Programs"], icon:"🛡️", description:"Proactive programs to prevent injury and maintain optimal health.", duration:"45 min" }
];
export const TIME_SLOTS = ["08:00 AM","09:00 AM","10:00 AM","11:00 AM","12:00 PM","02:00 PM","03:00 PM","04:00 PM","05:00 PM"];
